In [13]:
from joblib import load

# Load scaler từ file
loaded_scaler = load('scaler.joblib')

In [14]:
import pandas as pd 
import numpy as np 
import joblib
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
## Convert categorical data to numerical data
def convert_string_to_float(x):
    if type(x) == str:
        x = x.replace("(", "")
        x = x.replace(")", "")
        x = x.replace(",", "")
        return float(x)
    return x


In [15]:
clf = joblib.load("./catboost_model.pkl")

In [16]:
df = pd.read_excel("test_data.xlsx")
df.dropna(inplace=True)
y = df['TARGET']


In [17]:
df

CODE                    NAME STOCK EXCHANGE  YEAR  TARGET       EBIT  \
0  AAA  CTCP Nhựa An Phát Xanh           HOSE  2023       1  567110018   
1  AAA  CTCP Nhựa An Phát Xanh           HOSE  2019       1  827750342   

       EBITDA  TOTAL EQUITY/TOTAL ASSETS      EPS  CASH/TOTAL CURRENT ASSETS  \
0   834111528                  51.320000   224.74                  42.810000   
1  1080664256                   0.366437  2305.85                   0.000059   

   ...  LONG-TERM ASSETS/TOTAL ASSETS  QUICK RATIO  \
0  ...                      50.690000         1.32   
1  ...                       0.606693         0.95   

   Market Value of Total Equity / Book Values of Total Liabilities  \
0                                           0.643400                 
1                                           0.459455                 

   Sales/Total Assets  EBIT/Total Assets  Retain Earnings/Total Assets  \
0            1.094789           0.000049                      0.000059   
1            1.161603           0.000104                      0.000086   

   Working Capitals/Total Asset  ROIC  YEAR.1  NET INCOME/TOTAL ASSET  
0                      0.000168  4.88      21                0.025219  
1                      0.000217  9.39      17                0.057649  

[2 rows x 21 columns]

In [18]:
df.columns 

Index(['CODE', 'NAME', 'STOCK EXCHANGE', 'YEAR', 'TARGET', 'EBIT', 'EBITDA',
       'TOTAL EQUITY/TOTAL ASSETS', 'EPS', 'CASH/TOTAL CURRENT ASSETS',
       'TOTAL CURRENT ASSET/TOTAL ASSET', 'LONG-TERM ASSETS/TOTAL ASSETS',
       'QUICK RATIO',
       'Market Value of Total Equity / Book Values of Total Liabilities',
       'Sales/Total Assets', 'EBIT/Total Assets',
       'Retain Earnings/Total Assets', 'Working Capitals/Total Asset', 'ROIC',
       'YEAR.1', 'NET INCOME/TOTAL ASSET'],
      dtype='object')

In [19]:

df = pd.DataFrame(df, columns=['CODE', 'NAME', 
            'STOCK EXCHANGE', 'YEAR','EBIT', 'EBITDA',
            'TOTAL EQUITY/TOTAL ASSETS', 'EPS', 'CASH/TOTAL CURRENT ASSETS',
            'TOTAL CURRENT ASSET/TOTAL ASSET', 'LONG-TERM ASSETS/TOTAL ASSETS',
            'QUICK RATIO',
            'Market Value of Total Equity / Book Values of Total Liabilities',
            'Sales/Total Assets', 'EBIT/Total Assets',
            'Retain Earnings/Total Assets', 'Working Capitals/Total Asset', 'ROIC',
             'YEAR.1', 'NET INCOME/TOTAL ASSET'
        ],)

# Preprocess input data
df.drop(['CODE', 'NAME', 'YEAR'], axis=1, inplace=True)
try:
    df.drop(['TARGET'], axis=1, inplace=True)
except:
    pass
df['STOCK EXCHANGE'] = label_encoder.fit_transform(df['STOCK EXCHANGE'])
df = df.applymap(convert_string_to_float)
regression_fearture = df.columns.tolist()
regression_fearture.remove('STOCK EXCHANGE')
regression_fearture.remove('YEAR.1')
df[regression_fearture] = loaded_scaler.transform(df[regression_fearture])
df = df.applymap(convert_string_to_float)

/tmp/ipykernel_137472/3159249832.py:19: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(convert_string_to_float)
/tmp/ipykernel_137472/3159249832.py:24: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(convert_string_to_float)


In [26]:
df

STOCK EXCHANGE      EBIT    EBITDA  TOTAL EQUITY/TOTAL ASSETS       EPS  \
0               0  0.037491  0.069694                  -0.052447 -0.105533   
1               0  0.142830  0.153395                  -0.069445 -0.091958   

   CASH/TOTAL CURRENT ASSETS  TOTAL CURRENT ASSET/TOTAL ASSET  \
0                   3.246934                         0.508490   
1                  -0.466714                        -0.576136   

   LONG-TERM ASSETS/TOTAL ASSETS  QUICK RATIO  \
0                       0.490610    -0.153589   
1                      -0.288624    -0.229427   

   Market Value of Total Equity / Book Values of Total Liabilities  \
0                                          -0.261021                 
1                                          -0.276928                 

   Sales/Total Assets  EBIT/Total Assets  Retain Earnings/Total Assets  \
0           -0.078678          -0.076060                     -0.093038   
1           -0.073710          -0.050438                     -0.083623   

   Working Capitals/Total Asset      ROIC  YEAR.1  NET INCOME/TOTAL ASSET  
0                     -0.095705 -0.306689      21               -0.359962  
1                     -0.075297  0.075220      17                0.078456

In [21]:
final_data = pd.read_csv("final_data.csv")

In [22]:
final_data 

CODE                                    NAME  STOCK EXCHANGE  YEAR  \
0     AAA                  CTCP Nhựa An Phát Xanh               1  2019   
1     AAM                    CTCP Thủy sản MeKong               1  2019   
2     AAV                          CTCP AAV Group               0  2019   
3     ABT    CTCP Xuất nhập khẩu Thủy sản Bến Tre               1  2019   
4     ACC  CTCP Đầu tư và Xây dựng Bình Dương ACC               1  2019   
...   ...                                     ...             ...   ...   
2983  IDC               Tổng Công ty IDICO – CTCP               0  2020   
2984  TTF   CTCP Tập đoàn Kỹ nghệ gỗ Trường Thành               1  2020   
2985  MCO    CTCP Đầu tư và Xây dựng BDC Việt Nam               0  2022   
2986  MDC        CTCP Than Mông Dương - Vinacomin               0  2022   
2987  TTT      CTCP Du lịch - Thương mại Tây Ninh               0  2022   

      TARGET      EBIT    EBITDA  TOTAL EQUITY/TOTAL ASSETS       EPS  \
0        1.0  0.142830  0.153395                  -0.069445 -0.091958   
1        0.0 -0.187501 -0.208431                  -0.069458 -0.102743   
2        1.0 -0.173981 -0.196400                  -0.069405 -0.094619   
3        0.0 -0.169322 -0.192542                  -0.069307 -0.074574   
4        1.0 -0.167698 -0.190301                  -0.069394 -0.101800   
...      ...       ...       ...                        ...       ...   
2983     1.0  0.113035  0.179507                  -0.069471 -0.102428   
2984     1.0 -0.137310 -0.147362                  -0.069635 -0.106999   
2985     1.0 -0.191456 -0.212991                  -0.069438 -0.106833   
2986     0.0 -0.131278 -0.129928                  -0.069494 -0.098837   
2987     0.0 -0.170739 -0.193156                  -0.069262 -0.075901   

      CASH/TOTAL CURRENT ASSETS  ...  LONG-TERM ASSETS/TOTAL ASSETS  \
0                     -0.466714  ...                      -0.288624   
1                     -0.466719  ...                      -0.272364   
2                     -0.466713  ...                      -0.262996   
3                     -0.466715  ...                      -0.253317   
4                     -0.466718  ...                      -0.280108   
...                         ...  ...                            ...   
2983                  -0.466700  ...                      -0.285943   
2984                  -0.466715  ...                      -0.293098   
2985                   0.556032  ...                       0.237158   
2986                  -0.414671  ...                       0.441444   
2987                  -0.208212  ...                      -0.214824   

      QUICK RATIO  \
0       -0.229427   
1        0.578147   
2       -0.217129   
3       -0.262222   
4       -0.120794   
...           ...   
2983    -0.100297   
2984    -0.393402   
2985    -0.241725   
2986    -0.260172   
2987     1.760813   

      Market Value of Total Equity / Book Values of Total Liabilities  \
0                                             -0.276928                 
1                                              0.402189                 
2                                             -0.204175                 
3                                             -0.031056                 
4                                             -0.249133                 
...                                                 ...                 
2983                                          -0.226667                 
2984                                          -0.258089                 
2985                                          -0.299623                 
2986                                          -0.305191                 
2987                                           0.126216                 

      Sales/Total Assets  EBIT/Total Assets  Retain Earnings/Total Assets  \
0              -0.073710          -0.050438                     -0.083623   
1              -0.155687          -0.097903                     -0.111684   
2            

In [23]:
X = df 

In [24]:
from sklearn.metrics import classification_report

y_pred = clf.predict(X)
probabilities = clf.predict_proba(X)
report = classification_report(y, y_pred)
print(report)

ValueError: feature_names mismatch: ['EBIT', 'EBITDA', 'TOTAL EQUITY/TOTAL ASSETS', 'EPS', 'CASH/TOTAL CURRENT ASSETS', 'TOTAL CURRENT ASSET/TOTAL ASSET', 'LONG-TERM ASSETS/TOTAL ASSETS', 'QUICK RATIO', 'Market Value of Total Equity / Book Values of Total Liabilities', 'Sales/Total Assets', 'EBIT/Total Assets', 'Retain Earnings/Total Assets', 'Working Capitals/Total Asset', 'ROIC', 'YEAR.1', 'NET INCOME/TOTAL ASSET'] ['STOCK EXCHANGE', 'EBIT', 'EBITDA', 'TOTAL EQUITY/TOTAL ASSETS', 'EPS', 'CASH/TOTAL CURRENT ASSETS', 'TOTAL CURRENT ASSET/TOTAL ASSET', 'LONG-TERM ASSETS/TOTAL ASSETS', 'QUICK RATIO', 'Market Value of Total Equity / Book Values of Total Liabilities', 'Sales/Total Assets', 'EBIT/Total Assets', 'Retain Earnings/Total Assets', 'Working Capitals/Total Asset', 'ROIC', 'YEAR.1', 'NET INCOME/TOTAL ASSET']
training data did not have the following fields: STOCK EXCHANGE

In [ ]:
a = df.columns.tolist()

In [ ]:
a.remove('TARGET')

ValueError: list.remove(x): x not in list

In [ ]:
probabilities.shape

(2992, 2)

In [ ]:
probabilities

array([[3.6311150e-04, 9.9963689e-01],
       [9.9795467e-01, 2.0453045e-03],
       [5.0067902e-04, 9.9949932e-01],
       ...,
       [4.6253204e-05, 9.9995375e-01],
       [9.9861640e-01, 1.3835956e-03],
       [9.9973446e-01, 2.6554734e-04]], dtype=float32)

In [ ]:
for i in probabilities:
    print(i)

[3.631115e-04 9.996369e-01]
[0.99795467 0.0020453 ]
[5.006790e-04 9.994993e-01]
[0.99717146 0.00282855]
[2.2172928e-05 9.9997783e-01]
[2.0903349e-04 9.9979097e-01]
[9.9985147e-01 1.4856114e-04]
[0.99692357 0.00307644]
[5.6028366e-05 9.9994397e-01]
[9.9973524e-01 2.6476188e-04]
[0.0011161 0.9988839]
[9.997164e-01 2.836077e-04]
[8.7857246e-05 9.9991214e-01]
[9.9995071e-01 4.9290524e-05]
[9.9997032e-01 2.9661853e-05]
[9.9956870e-01 4.3129976e-04]
[9.9938726e-01 6.1270961e-04]
[5.1617622e-05 9.9994838e-01]
[9.9997139e-01 2.8582986e-05]
[9.9985057e-01 1.4942093e-04]
[5.6624413e-05 9.9994338e-01]
[0.96256423 0.03743579]
[2.5749207e-05 9.9997425e-01]
[0.99765164 0.00234834]
[6.7353249e-05 9.9993265e-01]
[3.838539e-05 9.999616e-01]
[8.881092e-05 9.999112e-01]
[0.99608344 0.00391656]
[9.999100e-01 8.999365e-05]
[9.9923736e-01 7.6261256e-04]
[9.999765e-01 2.347501e-05]
[1.9788742e-05 9.9998021e-01]
[0.99760693 0.00239308]
[9.9996704e-01 3.2946995e-05]
[3.8743019e-05 9.9996126e-01]
[9.9971145e-01

In [ ]:
import numpy as np

def softmax_aray(z):
    e_z = np.exp(z - np.max(z))  # Đảm bảo tính ổn định cho trường hợp số lớn
    return e_z / e_z.sum(axis=0)


In [ ]:
def softmax(z):
    softmax_output = np.array([])
    for i in z:
        softmax_output = np.append(softmax_output, softmax_aray(i))
    return softmax_output

In [ ]:
probabilities

array([[3.6311150e-04, 9.9963689e-01],
       [9.9795467e-01, 2.0453045e-03],
       [5.0067902e-04, 9.9949932e-01],
       ...,
       [4.6253204e-05, 9.9995375e-01],
       [9.9861640e-01, 1.3835956e-03],
       [9.9973446e-01, 2.6554734e-04]], dtype=float32)

In [ ]:
c = softmax(probabilities)
c

array([0.26908422, 0.73091578, 0.73025358, ..., 0.26948583, 0.73095411,
       0.26904583])

In [ ]:
for i in probabilities:
    pb = softmax_aray(i)
    print(pb)

[0.26908422 0.7309158 ]
[0.7302536  0.26974645]
[0.26913834 0.73086166]
[0.7299448  0.27005512]
[0.26895013 0.7310499 ]
[0.26902363 0.73097634]
[0.7310002  0.26899981]
[0.72984713 0.27015287]
[0.26896343 0.73103654]
[0.73095447 0.26904553]
[0.26938054 0.7306195 ]
[0.7309471  0.26905292]
[0.26897597 0.731024  ]
[0.7310392 0.2689608]
[0.73104686 0.26895308]
[0.73088896 0.26911104]
[0.7308176  0.26918244]
[0.2689617 0.7310383]
[0.73104733 0.26895264]
[0.7309998  0.26900017]
[0.26896366 0.7310363 ]
[0.71608585 0.2839141 ]
[0.26895154 0.73104846]
[0.7301342  0.26986587]
[0.2689679 0.7310321]
[0.26895648 0.7310435 ]
[0.26897636 0.73102367]
[0.72951573 0.27048427]
[0.7310232 0.2689768]
[0.7307586 0.2692414]
[0.73104936 0.26895064]
[0.2689492  0.73105085]
[0.7301165  0.26988345]
[0.7310456  0.26895437]
[0.26895663 0.73104334]
[0.7309451 0.2690549]
[0.72942597 0.270574  ]
[0.7308942  0.26910576]
[0.73019373 0.26980624]
[0.7308036  0.26919645]
[0.26896405 0.73103595]
[0.268957 0.731043]
[0.26904

In [ ]:
import torch
import torch
import torch.nn as nn
import torch.nn.functional as F

z = torch.tensor(probabilities)
softmax_output = F.softmax(z, dim=0)
print(softmax_output)


tensor([[0.0002, 0.0005],
        [0.0005, 0.0002],
        [0.0002, 0.0005],
        ...,
        [0.0002, 0.0005],
        [0.0005, 0.0002],
        [0.0005, 0.0002]])


In [ ]:
probabilities[0]

array([3.631115e-04, 9.996369e-01], dtype=float32)

In [ ]:
a = [[3.631115e-04, 9.996369e-01]]

In [ ]:
z = torch.tensor(a)
softmax_output = F.softmax(z, dim=0)
print(softmax_output)


tensor([[1., 1.]])


In [ ]:
output = softmax_aray(probabilities[0])

In [ ]:
output

array([0.26908422, 0.7309158 ], dtype=float32)

In [ ]:
max_values = np.max(probabilities, axis=1)

In [ ]:
max_values_scaled = np.round(max_values * 100, 2)
max_values_scaled

array([ 99.96,  99.8 ,  99.95, ..., 100.  ,  99.86,  99.97], dtype=float32)